# Generated by Django 5.2.1 on 2025-06-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instrutor',
            fields=[
                ('id', models.AutoField(help_text='Código do Instrutor', primary_key=True, serialize=False)),
                ('rg', models.IntegerField(help_text='Informe o RG do Instrutor (apenas números)', max_length=15)),
                ('nome', models.CharField(help_text='Informe o Nome do Instrutor', max_length=70)),
                ('dtnascimento', models.DateField(help_text='Informe a Data de Nascimento do Instrutor')),
                ('telefone', models.IntegerField(help_text='Informe o Telefone do Instrutor (apenas números)', max_length=9)),
                ('ddd', models.IntegerField(help_text='Informe o DDD do Telefone do Instrutor (apenas números)', max_length=2)),
            ],
        ),
    ]
