# Generated by Django 5.2.1 on 2025-06-09 22:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0001_initial'),
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, db_column='titulo_codigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='titulo.titulo'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='dtnascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 22, 36, 4, 227484, tzinfo=datetime.timezone.utc), help_text='Informe a Data de Nascimento do Instrutor', null=True),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='rg',
            field=models.CharField(help_text='Informe o RG do Instrutor (apenas números)', max_length=15),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='telefone',
            field=models.CharField(help_text='Informe o Telefone do Instrutor (apenas números)', max_length=9),
        ),
    ]
