# Generated by Django 5.2.1 on 2025-06-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeAtividade',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Tipo de atividade', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a Descrição do Tipo de atividade', max_length=70)),
            ],
        ),
    ]
