# Generated by Django 5.2.1 on 2025-06-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtinicial', models.DateField(help_text='Informe a Data de Início do Aluno')),
                ('dtfinal', models.DateField(help_text='Informe a Data Final do Aluno')),
                ('nome', models.CharField(help_text='Informe o Nome do Aluno', max_length=70)),
            ],
        ),
    ]
