# Generated by Django 5.2.1 on 2025-06-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.AutoField(help_text='Código da Matrícula do Aluno', primary_key=True, serialize=False),
        ),
    ]
