# Generated by Django 5.2.1 on 2025-06-09 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_remove_aluno_id_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dtfinal',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 22, 36, 4, 227484, tzinfo=datetime.timezone.utc), help_text='Informe a Data Final do Aluno', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dtinicial',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 22, 36, 4, 227484, tzinfo=datetime.timezone.utc), help_text='Informe a Data de Início do Aluno'),
        ),
    ]
