# Generated by Django 5.2.1 on 2025-06-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turma',
            fields=[
                ('numero', models.AutoField(help_text='Código da Turma', primary_key=True, serialize=False)),
                ('hraula', models.DateTimeField(help_text='Código do Instrutor')),
                ('drcaula', models.SmallIntegerField(help_text='Informe a Duração da Aula (em minutos)')),
                ('dtinicial', models.DateField(help_text='Data de Início da Aula')),
                ('dtfinal', models.DateField(help_text='Data de Fim da Aula')),
            ],
        ),
    ]
