# Generated by Django 5.2.1 on 2025-06-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_dtfinal_alter_aluno_dtinicial'),
        ('instrutor', '0002_instrutor_codigo_titulo_alter_instrutor_dtnascimento_and_more'),
        ('tiposdeatividade', '0002_alter_tipodeatividade_descricao'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='tiposdeatividade.tipodeatividade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='instrutor.instrutor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='matricula_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='aluno.aluno'),
        ),
    ]
